/**
 * Chinese unit name + pinyin lookup, keyed by [hskLevel][unitIndex].
 * Derived from scripts/thematic-units.ts — update both if unit names change.
 */
interface UnitNameEntry {
  zh: string;
  pinyin: string;
}

const unitNameMap: Record<number, Record<number, UnitNameEntry>> = {
  1: {
    1: { zh: "问候与基础", pinyin: "wènhòu yǔ jīchǔ" },
    2: { zh: "礼貌用语", pinyin: "lǐmào yòngyǔ" },
    3: { zh: "介绍与称呼", pinyin: "jièshào yǔ chēnghu" },
    4: { zh: "家庭", pinyin: "jiātíng" },
    5: { zh: "人物与称谓", pinyin: "rénwù yǔ chēngwèi" },
    6: { zh: "数字", pinyin: "shùzì" },
    7: { zh: "时间与日期", pinyin: "shíjiān yǔ rìqī" },
    8: { zh: "动作", pinyin: "dòngzuò" },
    9: { zh: "心理与情态动词", pinyin: "xīnlǐ yǔ qíngtài dòngcí" },
    10: { zh: "饮食", pinyin: "yǐnshí" },
    11: { zh: "描述", pinyin: "miáoshù" },
    12: { zh: "地点", pinyin: "dìdiǎn" },
    13: { zh: "事物", pinyin: "shìwù" },
    14: { zh: "位置与方位", pinyin: "wèizhì yǔ fāngwèi" },
    15: { zh: "天气与交通", pinyin: "tiānqì yǔ jiāotōng" },
  },
  2: {
    1: { zh: "大家庭", pinyin: "dà jiātíng" },
    2: { zh: "身体与健康", pinyin: "shēntǐ yǔ jiànkāng" },
    3: { zh: "数量与度量", pinyin: "shùliàng yǔ dùliàng" },
    4: { zh: "时间表达", pinyin: "shíjiān biǎodá" },
    5: { zh: "日常活动", pinyin: "rìcháng huódòng" },
    6: { zh: "美食与购物", pinyin: "měishí yǔ gòuwù" },
    7: { zh: "地点与方向", pinyin: "dìdiǎn yǔ fāngxiàng" },
    8: { zh: "交流", pinyin: "jiāoliú" },
    9: { zh: "描述", pinyin: "miáoshù" },
    10: { zh: "思维与情感", pinyin: "sīwéi yǔ qínggǎn" },
    11: { zh: "交通与旅行", pinyin: "jiāotōng yǔ lǚxíng" },
    12: { zh: "连接词与其他", pinyin: "liánjiē cí yǔ qítā" },
  },
  3: {
    1: { zh: "家庭与人际", pinyin: "jiātíng yǔ rénjì" },
    2: { zh: "身体与外貌", pinyin: "shēntǐ yǔ wàimào" },
    3: { zh: "健康与情感", pinyin: "jiànkāng yǔ qínggǎn" },
    4: { zh: "食物与厨房", pinyin: "shíwù yǔ chúfáng" },
    5: { zh: "服饰与物品", pinyin: "fúshì yǔ wùpǐn" },
    6: { zh: "地点与方位", pinyin: "dìdiǎn yǔ fāngwèi" },
    7: { zh: "自然与环境", pinyin: "zìrán yǔ huánjìng" },
    8: { zh: "学校与学习", pinyin: "xuéxiào yǔ xuéxí" },
    9: { zh: "工作与社会", pinyin: "gōngzuò yǔ shèhuì" },
    10: { zh: "身体动作", pinyin: "shēntǐ dòngzuò" },
    11: { zh: "心理动词", pinyin: "xīnlǐ dòngcí" },
    12: { zh: "形容描述", pinyin: "xíngróng miáoshù" },
    13: { zh: "时间与频率", pinyin: "shíjiān yǔ pínlǜ" },
    14: { zh: "程度与比较", pinyin: "chéngdù yǔ bǐjiào" },
    15: { zh: "语法与其他", pinyin: "yǔfǎ yǔ qítā" },
  },
  4: {
    1: { zh: "情感与性格", pinyin: "qínggǎn yǔ xìnggé" },
    2: { zh: "家庭与人物", pinyin: "jiātíng yǔ rénwù" },
    3: { zh: "身体与健康", pinyin: "shēntǐ yǔ jiànkāng" },
    4: { zh: "饮食", pinyin: "yǐnshí" },
    5: { zh: "居家与物品", pinyin: "jūjiā yǔ wùpǐn" },
    6: { zh: "形容描述", pinyin: "xíngróng miáoshù" },
    7: { zh: "工作与职业", pinyin: "gōngzuò yǔ zhíyè" },
    8: { zh: "教育与知识", pinyin: "jiàoyù yǔ zhīshi" },
    9: { zh: "商业与经济", pinyin: "shāngyè yǔ jīngjì" },
    10: { zh: "自然与地理", pinyin: "zìrán yǔ dìlǐ" },
    11: { zh: "交通与旅行", pinyin: "jiāotōng yǔ lǚxíng" },
    12: { zh: "社交互动", pinyin: "shèjiāo hùdòng" },
    13: { zh: "身体动作", pinyin: "shēntǐ dòngzuò" },
    14: { zh: "思维与表达", pinyin: "sīwéi yǔ biǎodá" },
    15: { zh: "抽象与语法", pinyin: "chōuxiàng yǔ yǔfǎ" },
  },
  5: {
    1: { zh: "情感与心理", pinyin: "qínggǎn yǔ xīnlǐ" },
    2: { zh: "家庭与人物", pinyin: "jiātíng yǔ rénwù" },
    3: { zh: "身体与健康", pinyin: "shēntǐ yǔ jiànkāng" },
    4: { zh: "食物与烹饪", pinyin: "shíwù yǔ pēngrèn" },
    5: { zh: "居家与日常", pinyin: "jūjiā yǔ rìcháng" },
    6: { zh: "服饰与时尚", pinyin: "fúshì yǔ shíshàng" },
    7: { zh: "自然与动物", pinyin: "zìrán yǔ dòngwù" },
    8: { zh: "建筑与地点", pinyin: "jiànzhù yǔ dìdiǎn" },
    9: { zh: "教育与学习", pinyin: "jiàoyù yǔ xuéxí" },
    10: { zh: "工作与商业", pinyin: "gōngzuò yǔ shāngyè" },
    11: { zh: "政治与社会", pinyin: "zhèngzhì yǔ shèhuì" },
    12: { zh: "传媒与通讯", pinyin: "chuánméi yǔ tōngxùn" },
    13: { zh: "科技", pinyin: "kējì" },
    14: { zh: "动作", pinyin: "dòngzuò" },
    15: { zh: "思维与认知", pinyin: "sīwéi yǔ rènzhī" },
    16: { zh: "形容描述", pinyin: "xíngróng miáoshù" },
    17: { zh: "时间与顺序", pinyin: "shíjiān yǔ shùnxù" },
    18: { zh: "数量与度量", pinyin: "shùliàng yǔ dùliàng" },
    19: { zh: "语法与功能词", pinyin: "yǔfǎ yǔ gōngnéng cí" },
  },
  6: {
    1: { zh: "情感与心理", pinyin: "qínggǎn yǔ xīnlǐ" },
    2: { zh: "人物与社交", pinyin: "rénwù yǔ shèjiāo" },
    3: { zh: "身体与健康", pinyin: "shēntǐ yǔ jiànkāng" },
    4: { zh: "食物与烹饪", pinyin: "shíwù yǔ pēngrèn" },
    5: { zh: "自然与地理", pinyin: "zìrán yǔ dìlǐ" },
    6: { zh: "居家与日常", pinyin: "jūjiā yǔ rìcháng" },
    7: { zh: "教育与文化", pinyin: "jiàoyù yǔ wénhuà" },
    8: { zh: "军事与法律", pinyin: "jūnshì yǔ fǎlǜ" },
    9: { zh: "政治与政府", pinyin: "zhèngzhì yǔ zhèngfǔ" },
    10: { zh: "经济与商业", pinyin: "jīngjì yǔ shāngyè" },
    11: { zh: "语言与交际", pinyin: "yǔyán yǔ jiāojì" },
    12: { zh: "动作", pinyin: "dòngzuò" },
    13: { zh: "自然与科学", pinyin: "zìrán yǔ kēxué" },
    14: { zh: "工作与职场", pinyin: "gōngzuò yǔ zhíchǎng" },
    15: { zh: "描述词（一）", pinyin: "miáoshù cí (yī)" },
    16: { zh: "描述词（二）", pinyin: "miáoshù cí (èr)" },
    17: { zh: "成语与熟语", pinyin: "chéngyǔ yǔ shúyǔ" },
    18: { zh: "社交与行为", pinyin: "shèjiāo yǔ xíngwéi" },
    19: { zh: "行政与管理", pinyin: "xíngzhèng yǔ guǎnlǐ" },
    20: { zh: "时间与变化", pinyin: "shíjiān yǔ biànhuà" },
    21: { zh: "数量与程度", pinyin: "shùliàng yǔ chéngdù" },
    22: { zh: "自然物质", pinyin: "zìrán wùzhì" },
    23: { zh: "思维活动", pinyin: "sīwéi huódòng" },
    24: { zh: "交际动词", pinyin: "jiāojì dòngcí" },
    25: { zh: "动作（其他）", pinyin: "dòngzuò (qítā)" },
    26: { zh: "动词：人际", pinyin: "dòngcí: rénjì" },
    27: { zh: "动词：职业", pinyin: "dòngcí: zhíyè" },
    28: { zh: "动词：一般（一）", pinyin: "dòngcí: yībān (yī)" },
    29: { zh: "动词：一般（二）", pinyin: "dòngcí: yībān (èr)" },
    30: { zh: "抽象名词（一）", pinyin: "chōuxiàng míngcí (yī)" },
    31: { zh: "抽象名词（二）", pinyin: "chōuxiàng míngcí (èr)" },
    32: { zh: "具体名词", pinyin: "jùtǐ míngcí" },
    33: { zh: "副词与连接词", pinyin: "fùcí yǔ liánjiē cí" },
    34: { zh: "形容词（一）", pinyin: "xíngróngcí (yī)" },
    35: { zh: "形容词（二）", pinyin: "xíngróngcí (èr)" },
    36: { zh: "其他词汇", pinyin: "qítā cíhuì" },
  },
};

/** Returns the Chinese unit name for a given HSK level and unit index, or undefined. */
export function getUnitNameZh(hskLevel: number, unitIndex: number): string | undefined {
  return unitNameMap[hskLevel]?.[unitIndex]?.zh;
}

/** Returns the pinyin for a given HSK level and unit index, or undefined. */
export function getUnitNamePinyin(hskLevel: number, unitIndex: number): string | undefined {
  return unitNameMap[hskLevel]?.[unitIndex]?.pinyin;
}
