#!/usr/bin/env tsx
/**
 * Apply corrections from corrections.json to the vocab JSON files.
 *
 * Usage:
 *   npm run apply-corrections
 *
 * Reads `corrections.json` from the project root (generated by the
 * in-app "Export Corrections" button on the characters review page).
 *
 * For each correction entry, finds the matching word in the appropriate
 * public/data/hsk{N}-vocab.json file, updates pinyin and/or meaning,
 * saves the file back, and prints a diff of every change.
 */

import { readFileSync, writeFileSync, existsSync } from "fs";
import { join } from "path";

interface WordCorrection {
  id: string;
  pinyin?: string;
  meaning?: string;
  correctedAt: string;
}

interface HskWord {
  id: string;
  simplified: string;
  pinyin: string;
  meaning: string;
  [key: string]: unknown;
}

const ROOT = join(__dirname, "..");
const DATA_DIR = join(ROOT, "public", "data");
const CORRECTIONS_FILE = join(ROOT, "corrections.json");

if (!existsSync(CORRECTIONS_FILE)) {
  console.error(`Error: corrections.json not found at ${CORRECTIONS_FILE}`);
  console.error("Export corrections from the app first (characters review → 'Export Corrections' button).");
  process.exit(1);
}

const corrections: WordCorrection[] = JSON.parse(
  readFileSync(CORRECTIONS_FILE, "utf-8"),
);

if (corrections.length === 0) {
  console.log("No corrections found in corrections.json.");
  process.exit(0);
}

console.log(`Found ${corrections.length} correction(s). Applying...\n`);

// Group corrections by HSK level (derived from word id prefix "hsk{N}-")
const byLevel = new Map<number, WordCorrection[]>();
for (const c of corrections) {
  const match = c.id.match(/^hsk(\d)/);
  if (!match) {
    console.warn(`  [SKIP] Unknown id format (expected hsk{N}-...): ${c.id}`);
    continue;
  }
  const level = parseInt(match[1]);
  const list = byLevel.get(level) ?? [];
  list.push(c);
  byLevel.set(level, list);
}

let totalChanges = 0;

for (const [level, levelCorrections] of Array.from(byLevel.entries()).sort(([a], [b]) => a - b)) {
  const filePath = join(DATA_DIR, `hsk${level}-vocab.json`);

  if (!existsSync(filePath)) {
    console.warn(`  [SKIP] File not found: ${filePath}`);
    continue;
  }

  const words: HskWord[] = JSON.parse(readFileSync(filePath, "utf-8"));
  const wordMap = new Map(words.map((w) => [w.id, w]));
  let changed = false;

  console.log(`HSK ${level} (${filePath.replace(ROOT + "/", "")})`);

  for (const corr of levelCorrections) {
    const word = wordMap.get(corr.id);
    if (!word) {
      console.warn(`  [SKIP] Word not found: ${corr.id}`);
      continue;
    }

    if (corr.pinyin !== undefined && corr.pinyin !== word.pinyin) {
      console.log(`  [PINYIN]  ${corr.id} (${word.simplified}): "${word.pinyin}" → "${corr.pinyin}"`);
      word.pinyin = corr.pinyin;
      changed = true;
      totalChanges++;
    }

    if (corr.meaning !== undefined && corr.meaning !== word.meaning) {
      console.log(`  [MEANING] ${corr.id} (${word.simplified}): "${word.meaning}" → "${corr.meaning}"`);
      word.meaning = corr.meaning;
      changed = true;
      totalChanges++;
    }
  }

  if (changed) {
    writeFileSync(filePath, JSON.stringify(words, null, 2) + "\n", "utf-8");
    console.log(`  ✓ Saved.\n`);
  } else {
    console.log(`  No changes.\n`);
  }
}

console.log(`Done. ${totalChanges} field(s) updated across ${byLevel.size} level file(s).`);
