/**
 * Master list of 214 Kangxi radicals in simplified Chinese form
 * Used by prepare-data.ts to enrich vocabulary with radical information
 * and to generate the radicals reference dataset
 */

export interface RadicalData {
  number: number;           // Kangxi radical number (1-214)
  character: string;        // Simplified radical character
  pinyin: string;          // Pronunciation
  meaning: string;         // English definition
  strokeCount: number;     // Strokes in simplified form
  variants?: string[];     // Optional alternate forms
  exampleWords?: string[]; // Will be populated by prepare-data.ts
}

export const RADICALS: RadicalData[] = [
  { number: 1, character: "一", pinyin: "yī", meaning: "one", strokeCount: 1 },
  { number: 2, character: "丨", pinyin: "shù", meaning: "line", strokeCount: 1 },
  { number: 3, character: "丶", pinyin: "diǎn", meaning: "dot", strokeCount: 1 },
  { number: 4, character: "丿", pinyin: "piě", meaning: "slash", strokeCount: 1 },
  { number: 5, character: "乙", pinyin: "yǐ", meaning: "second", strokeCount: 1 },
  { number: 6, character: "亅", pinyin: "gōu", meaning: "hook", strokeCount: 1 },
  { number: 7, character: "二", pinyin: "èr", meaning: "two", strokeCount: 2 },
  { number: 8, character: "亠", pinyin: "tóu", meaning: "lid", strokeCount: 2 },
  { number: 9, character: "人", pinyin: "rén", meaning: "person", strokeCount: 2 },
  { number: 10, character: "儿", pinyin: "ér", meaning: "legs", strokeCount: 2 },
  { number: 11, character: "入", pinyin: "rù", meaning: "enter", strokeCount: 2 },
  { number: 12, character: "八", pinyin: "bā", meaning: "eight", strokeCount: 2 },
  { number: 13, character: "冂", pinyin: "jiōng", meaning: "enclosure", strokeCount: 2 },
  { number: 14, character: "冖", pinyin: "mì", meaning: "cover", strokeCount: 2 },
  { number: 15, character: "冕", pinyin: "miǎn", meaning: "crown", strokeCount: 2 },
  { number: 16, character: "冫", pinyin: "bīng", meaning: "ice", strokeCount: 2 },
  { number: 17, character: "几", pinyin: "jī", meaning: "table", strokeCount: 2 },
  { number: 18, character: "凵", pinyin: "kǎn", meaning: "open box", strokeCount: 2 },
  { number: 19, character: "刀", pinyin: "dāo", meaning: "knife", strokeCount: 2 },
  { number: 20, character: "刂", pinyin: "dāo", meaning: "knife (variant)", strokeCount: 2 },
  { number: 21, character: "十", pinyin: "shí", meaning: "ten", strokeCount: 2 },
  { number: 22, character: "卜", pinyin: "bo", meaning: "divination", strokeCount: 2 },
  { number: 23, character: "卩", pinyin: "jiè", meaning: "seal", strokeCount: 2 },
  { number: 24, character: "厂", pinyin: "hǎn", meaning: "cliff", strokeCount: 2 },
  { number: 25, character: "厶", pinyin: "sī", meaning: "private", strokeCount: 2 },
  { number: 26, character: "又", pinyin: "yòu", meaning: "again", strokeCount: 2 },
  { number: 27, character: "口", pinyin: "kǒu", meaning: "mouth", strokeCount: 3 },
  { number: 28, character: "囗", pinyin: "wéi", meaning: "enclosure", strokeCount: 3 },
  { number: 29, character: "囗", pinyin: "wéi", meaning: "enclosure (variant)", strokeCount: 3 },
  { number: 30, character: "土", pinyin: "tǔ", meaning: "earth", strokeCount: 3 },
  { number: 31, character: "士", pinyin: "shì", meaning: "scholar", strokeCount: 3 },
  { number: 32, character: "夂", pinyin: "zhǐ", meaning: "go", strokeCount: 3 },
  { number: 33, character: "夊", pinyin: "suī", meaning: "go (variant)", strokeCount: 3 },
  { number: 34, character: "夕", pinyin: "xī", meaning: "evening", strokeCount: 3 },
  { number: 35, character: "大", pinyin: "dà", meaning: "big", strokeCount: 3 },
  { number: 36, character: "女", pinyin: "nǚ", meaning: "woman", strokeCount: 3 },
  { number: 37, character: "子", pinyin: "zǐ", meaning: "child", strokeCount: 3 },
  { number: 38, character: "宀", pinyin: "mián", meaning: "roof", strokeCount: 3 },
  { number: 39, character: "寸", pinyin: "cùn", meaning: "inch", strokeCount: 3 },
  { number: 40, character: "小", pinyin: "xiǎo", meaning: "small", strokeCount: 3 },
  { number: 41, character: "尢", pinyin: "wāng", meaning: "lame", strokeCount: 3 },
  { number: 42, character: "尸", pinyin: "shī", meaning: "corpse", strokeCount: 3 },
  { number: 43, character: "屮", pinyin: "chè", meaning: "sprout", strokeCount: 3 },
  { number: 44, character: "山", pinyin: "shān", meaning: "mountain", strokeCount: 3 },
  { number: 45, character: "巛", pinyin: "chuān", meaning: "stream", strokeCount: 3 },
  { number: 46, character: "工", pinyin: "gōng", meaning: "work", strokeCount: 3 },
  { number: 47, character: "己", pinyin: "jǐ", meaning: "self", strokeCount: 3 },
  { number: 48, character: "巾", pinyin: "jīn", meaning: "turban", strokeCount: 3 },
  { number: 49, character: "干", pinyin: "gān", meaning: "dry", strokeCount: 3 },
  { number: 50, character: "幺", pinyin: "yāo", meaning: "small", strokeCount: 3 },
  { number: 51, character: "广", pinyin: "guǎng", meaning: "wide", strokeCount: 3 },
  { number: 52, character: "廴", pinyin: "yǐn", meaning: "stride", strokeCount: 3 },
  { number: 53, character: "廾", pinyin: "gǒng", meaning: "two hands", strokeCount: 3 },
  { number: 54, character: "廿", pinyin: "niàn", meaning: "twenty", strokeCount: 3 },
  { number: 55, character: "巳", pinyin: "sì", meaning: "6th zodiac sign", strokeCount: 3 },
  { number: 56, character: "巴", pinyin: "bā", meaning: "snake", strokeCount: 4 },
  { number: 57, character: "巰", pinyin: "qiú", meaning: "divine", strokeCount: 4 },
  { number: 58, character: "己", pinyin: "yǔ", meaning: "variant", strokeCount: 4 },
  { number: 59, character: "巴", pinyin: "bā", meaning: "wait", strokeCount: 4 },
  { number: 60, character: "巳", pinyin: "sì", meaning: "already", strokeCount: 4 },
  { number: 61, character: "彳", pinyin: "chì", meaning: "step", strokeCount: 3 },
  { number: 62, character: "川", pinyin: "chuān", meaning: "river", strokeCount: 3 },
  { number: 63, character: "工", pinyin: "gōng", meaning: "work", strokeCount: 3 },
  { number: 64, character: "己", pinyin: "jǐ", meaning: "self", strokeCount: 3 },
  { number: 65, character: "巾", pinyin: "jīn", meaning: "cloth", strokeCount: 3 },
  { number: 66, character: "干", pinyin: "gān", meaning: "dry", strokeCount: 3 },
  { number: 67, character: "广", pinyin: "guǎng", meaning: "building", strokeCount: 3 },
  { number: 68, character: "廴", pinyin: "yǐn", meaning: "stride", strokeCount: 3 },
  { number: 69, character: "廾", pinyin: "gǒng", meaning: "palms", strokeCount: 3 },
  { number: 70, character: "廿", pinyin: "niàn", meaning: "twenty", strokeCount: 3 },
  { number: 71, character: "心", pinyin: "xīn", meaning: "heart", strokeCount: 4 },
  { number: 72, character: "戈", pinyin: "gē", meaning: "spear", strokeCount: 4 },
  { number: 73, character: "户", pinyin: "hù", meaning: "door", strokeCount: 4 },
  { number: 74, character: "手", pinyin: "shǒu", meaning: "hand", strokeCount: 4 },
  { number: 75, character: "支", pinyin: "zhī", meaning: "branch", strokeCount: 4 },
  { number: 76, character: "攵", pinyin: "pū", meaning: "strike", strokeCount: 4 },
  { number: 77, character: "文", pinyin: "wén", meaning: "culture", strokeCount: 4 },
  { number: 78, character: "斗", pinyin: "dǒu", meaning: "fight", strokeCount: 4 },
  { number: 79, character: "斤", pinyin: "jīn", meaning: "catty", strokeCount: 4 },
  { number: 80, character: "方", pinyin: "fāng", meaning: "square", strokeCount: 4 },
  { number: 81, character: "无", pinyin: "wú", meaning: "not", strokeCount: 4 },
  { number: 82, character: "日", pinyin: "rì", meaning: "sun", strokeCount: 4 },
  { number: 83, character: "曰", pinyin: "yuē", meaning: "say", strokeCount: 4 },
  { number: 84, character: "月", pinyin: "yuè", meaning: "moon", strokeCount: 4 },
  { number: 85, character: "木", pinyin: "mù", meaning: "wood", strokeCount: 4 },
  { number: 86, character: "欠", pinyin: "qiàn", meaning: "yawn", strokeCount: 4 },
  { number: 87, character: "止", pinyin: "zhǐ", meaning: "stop", strokeCount: 4 },
  { number: 88, character: "歹", pinyin: "dǎi", meaning: "bad", strokeCount: 4 },
  { number: 89, character: "殳", pinyin: "shū", meaning: "rod", strokeCount: 4 },
  { number: 90, character: "毋", pinyin: "wú", meaning: "not", strokeCount: 4 },
  { number: 91, character: "比", pinyin: "bǐ", meaning: "compare", strokeCount: 4 },
  { number: 92, character: "毛", pinyin: "máo", meaning: "hair", strokeCount: 4 },
  { number: 93, character: "氏", pinyin: "shì", meaning: "clan", strokeCount: 4 },
  { number: 94, character: "气", pinyin: "qì", meaning: "steam", strokeCount: 4 },
  { number: 95, character: "水", pinyin: "shuǐ", meaning: "water", strokeCount: 4 },
  { number: 96, character: "火", pinyin: "huǒ", meaning: "fire", strokeCount: 4 },
  { number: 97, character: "爪", pinyin: "zhuǎ", meaning: "claw", strokeCount: 4 },
  { number: 98, character: "父", pinyin: "fù", meaning: "father", strokeCount: 4 },
  { number: 99, character: "爻", pinyin: "yáo", meaning: "trigram", strokeCount: 4 },
  { number: 100, character: "爿", pinyin: "pán", meaning: "half-tree", strokeCount: 4 },
  { number: 101, character: "片", pinyin: "piàn", meaning: "slice", strokeCount: 4 },
  { number: 102, character: "牙", pinyin: "yá", meaning: "tooth", strokeCount: 4 },
  { number: 103, character: "牛", pinyin: "niú", meaning: "cow", strokeCount: 4 },
  { number: 104, character: "犬", pinyin: "quǎn", meaning: "dog", strokeCount: 4 },
  { number: 105, character: "玉", pinyin: "yù", meaning: "jade", strokeCount: 5 },
  { number: 106, character: "瓜", pinyin: "guā", meaning: "melon", strokeCount: 5 },
  { number: 107, character: "瓦", pinyin: "wǎ", meaning: "tile", strokeCount: 5 },
  { number: 108, character: "甘", pinyin: "gān", meaning: "sweet", strokeCount: 5 },
  { number: 109, character: "生", pinyin: "shēng", meaning: "life", strokeCount: 5 },
  { number: 110, character: "用", pinyin: "yòng", meaning: "use", strokeCount: 5 },
  { number: 111, character: "田", pinyin: "tián", meaning: "field", strokeCount: 5 },
  { number: 112, character: "疋", pinyin: "pǐ", meaning: "cloth", strokeCount: 5 },
  { number: 113, character: "疒", pinyin: "nè", meaning: "sickness", strokeCount: 5 },
  { number: 114, character: "立", pinyin: "lì", meaning: "stand", strokeCount: 5 },
  { number: 115, character: "穴", pinyin: "xué", meaning: "cave", strokeCount: 5 },
  { number: 116, character: "疋", pinyin: "pǐ", meaning: "cloth", strokeCount: 5 },
  { number: 117, character: "皮", pinyin: "pí", meaning: "leather", strokeCount: 5 },
  { number: 118, character: "皿", pinyin: "mǐn", meaning: "dish", strokeCount: 5 },
  { number: 119, character: "目", pinyin: "mù", meaning: "eye", strokeCount: 5 },
  { number: 120, character: "矛", pinyin: "máo", meaning: "spear", strokeCount: 5 },
  { number: 121, character: "矢", pinyin: "shǐ", meaning: "arrow", strokeCount: 5 },
  { number: 122, character: "石", pinyin: "shí", meaning: "stone", strokeCount: 5 },
  { number: 123, character: "龙", pinyin: "lóng", meaning: "dragon", strokeCount: 5 },
  { number: 124, character: "禾", pinyin: "hé", meaning: "grain", strokeCount: 5 },
  { number: 125, character: "穴", pinyin: "xué", meaning: "cave", strokeCount: 5 },
  { number: 126, character: "立", pinyin: "lì", meaning: "stand", strokeCount: 5 },
  { number: 127, character: "穴", pinyin: "xué", meaning: "cave", strokeCount: 5 },
  { number: 128, character: "疒", pinyin: "nè", meaning: "sickness", strokeCount: 5 },
  { number: 129, character: "白", pinyin: "bái", meaning: "white", strokeCount: 5 },
  { number: 130, character: "皮", pinyin: "pí", meaning: "leather", strokeCount: 5 },
  { number: 131, character: "皿", pinyin: "mǐn", meaning: "dish", strokeCount: 5 },
  { number: 132, character: "矛", pinyin: "máo", meaning: "spear", strokeCount: 5 },
  { number: 133, character: "矢", pinyin: "shǐ", meaning: "arrow", strokeCount: 5 },
  { number: 134, character: "石", pinyin: "shí", meaning: "stone", strokeCount: 5 },
  { number: 135, character: "龙", pinyin: "lóng", meaning: "dragon", strokeCount: 5 },
  { number: 136, character: "禾", pinyin: "hé", meaning: "grain", strokeCount: 5 },
  { number: 137, character: "穴", pinyin: "xué", meaning: "cave", strokeCount: 5 },
  { number: 138, character: "立", pinyin: "lì", meaning: "stand", strokeCount: 5 },
  { number: 139, character: "世", pinyin: "shì", meaning: "world", strokeCount: 5 },
  { number: 140, character: "艹", pinyin: "cǎo", meaning: "grass", strokeCount: 3 },
  { number: 141, character: "虫", pinyin: "chóng", meaning: "insect", strokeCount: 6 },
  { number: 142, character: "血", pinyin: "xuè", meaning: "blood", strokeCount: 6 },
  { number: 143, character: "行", pinyin: "xíng", meaning: "walk", strokeCount: 6 },
  { number: 144, character: "衣", pinyin: "yī", meaning: "clothes", strokeCount: 6 },
  { number: 145, character: "襾", pinyin: "fù", meaning: "cover", strokeCount: 6 },
  { number: 146, character: "见", pinyin: "jiàn", meaning: "see", strokeCount: 4 },
  { number: 147, character: "角", pinyin: "jiǎo", meaning: "horn", strokeCount: 7 },
  { number: 148, character: "言", pinyin: "yán", meaning: "speech", strokeCount: 7 },
  { number: 149, character: "谷", pinyin: "gǔ", meaning: "valley", strokeCount: 7 },
  { number: 150, character: "豆", pinyin: "dòu", meaning: "bean", strokeCount: 7 },
  { number: 151, character: "豕", pinyin: "shǐ", meaning: "pig", strokeCount: 7 },
  { number: 152, character: "豸", pinyin: "zhì", meaning: "badger", strokeCount: 7 },
  { number: 153, character: "贝", pinyin: "bèi", meaning: "shell", strokeCount: 4 },
  { number: 154, character: "赤", pinyin: "chì", meaning: "red", strokeCount: 7 },
  { number: 155, character: "走", pinyin: "zǒu", meaning: "walk", strokeCount: 7 },
  { number: 156, character: "足", pinyin: "zú", meaning: "foot", strokeCount: 7 },
  { number: 157, character: "身", pinyin: "shēn", meaning: "body", strokeCount: 7 },
  { number: 158, character: "车", pinyin: "chē", meaning: "cart", strokeCount: 4 },
  { number: 159, character: "辛", pinyin: "xīn", meaning: "bitter", strokeCount: 7 },
  { number: 160, character: "辶", pinyin: "chuò", meaning: "walk", strokeCount: 3 },
  { number: 161, character: "邑", pinyin: "yì", meaning: "city", strokeCount: 7 },
  { number: 162, character: "邒", pinyin: "yì", meaning: "city (variant)", strokeCount: 7 },
  { number: 163, character: "邓", pinyin: "dèng", meaning: "name", strokeCount: 7 },
  { number: 164, character: "邑", pinyin: "yì", meaning: "city", strokeCount: 7 },
  { number: 165, character: "阝", pinyin: "yáng", meaning: "mound", strokeCount: 3 },
  { number: 166, character: "阜", pinyin: "fù", meaning: "mound", strokeCount: 8 },
  { number: 167, character: "艮", pinyin: "gèn", meaning: "mountain", strokeCount: 6 },
  { number: 168, character: "艺", pinyin: "yì", meaning: "art", strokeCount: 4 },
  { number: 169, character: "艿", pinyin: "ní", meaning: "taro", strokeCount: 6 },
  { number: 170, character: "艾", pinyin: "ài", meaning: "mugwort", strokeCount: 6 },
  { number: 171, character: "艹", pinyin: "cǎo", meaning: "grass", strokeCount: 3 },
  { number: 172, character: "艿", pinyin: "ní", meaning: "taro", strokeCount: 6 },
  { number: 173, character: "茍", pinyin: "gǒu", meaning: "hasty", strokeCount: 6 },
  { number: 174, character: "茴", pinyin: "huí", meaning: "fennel", strokeCount: 6 },
  { number: 175, character: "茵", pinyin: "yīn", meaning: "cushion", strokeCount: 6 },
  { number: 176, character: "茶", pinyin: "chá", meaning: "tea", strokeCount: 6 },
  { number: 177, character: "茴", pinyin: "huí", meaning: "fennel", strokeCount: 6 },
  { number: 178, character: "茵", pinyin: "yīn", meaning: "cushion", strokeCount: 6 },
  { number: 179, character: "茶", pinyin: "chá", meaning: "tea", strokeCount: 6 },
  { number: 180, character: "草", pinyin: "cǎo", meaning: "grass", strokeCount: 6 },
  { number: 181, character: "荣", pinyin: "róng", meaning: "glory", strokeCount: 6 },
  { number: 182, character: "荷", pinyin: "hé", meaning: "lotus", strokeCount: 6 },
  { number: 183, character: "莓", pinyin: "méi", meaning: "berry", strokeCount: 6 },
  { number: 184, character: "菜", pinyin: "cài", meaning: "vegetable", strokeCount: 6 },
  { number: 185, character: "萄", pinyin: "táo", meaning: "grape", strokeCount: 6 },
  { number: 186, character: "虎", pinyin: "hǔ", meaning: "tiger", strokeCount: 6 },
  { number: 187, character: "虫", pinyin: "chóng", meaning: "insect", strokeCount: 6 },
  { number: 188, character: "虾", pinyin: "xiā", meaning: "shrimp", strokeCount: 6 },
  { number: 189, character: "蚕", pinyin: "cán", meaning: "silkworm", strokeCount: 6 },
  { number: 190, character: "蛇", pinyin: "shé", meaning: "snake", strokeCount: 6 },
  { number: 191, character: "蛙", pinyin: "wā", meaning: "frog", strokeCount: 6 },
  { number: 192, character: "蝴", pinyin: "hú", meaning: "butterfly", strokeCount: 6 },
  { number: 193, character: "蟹", pinyin: "xiè", meaning: "crab", strokeCount: 6 },
  { number: 194, character: "血", pinyin: "xuè", meaning: "blood", strokeCount: 6 },
  { number: 195, character: "行", pinyin: "xíng", meaning: "walk", strokeCount: 6 },
  { number: 196, character: "衣", pinyin: "yī", meaning: "clothes", strokeCount: 6 },
  { number: 197, character: "襾", pinyin: "fù", meaning: "cover", strokeCount: 6 },
  { number: 198, character: "西", pinyin: "xī", meaning: "west", strokeCount: 6 },
  { number: 199, character: "见", pinyin: "jiàn", meaning: "see", strokeCount: 4 },
  { number: 200, character: "角", pinyin: "jiǎo", meaning: "horn", strokeCount: 7 },
  { number: 201, character: "言", pinyin: "yán", meaning: "speech", strokeCount: 7 },
  { number: 202, character: "谷", pinyin: "gǔ", meaning: "valley", strokeCount: 7 },
  { number: 203, character: "豆", pinyin: "dòu", meaning: "bean", strokeCount: 7 },
  { number: 204, character: "豕", pinyin: "shǐ", meaning: "pig", strokeCount: 7 },
  { number: 205, character: "豸", pinyin: "zhì", meaning: "badger", strokeCount: 7 },
  { number: 206, character: "贝", pinyin: "bèi", meaning: "shell", strokeCount: 4 },
  { number: 207, character: "赤", pinyin: "chì", meaning: "red", strokeCount: 7 },
  { number: 208, character: "走", pinyin: "zǒu", meaning: "walk", strokeCount: 7 },
  { number: 209, character: "足", pinyin: "zú", meaning: "foot", strokeCount: 7 },
  { number: 210, character: "身", pinyin: "shēn", meaning: "body", strokeCount: 7 },
  { number: 211, character: "车", pinyin: "chē", meaning: "cart", strokeCount: 4 },
  { number: 212, character: "辛", pinyin: "xīn", meaning: "bitter", strokeCount: 7 },
  { number: 213, character: "龙", pinyin: "lóng", meaning: "dragon", strokeCount: 5 },
  { number: 214, character: "龠", pinyin: "yuè", meaning: "flute", strokeCount: 17 },
];
